---
- name: Calling Groovy script {{ script_name }}
  uri:
    url: "http://admin:{{ current_nexus_admin_password }}@127.0.0.1:{{ nexus_default_port }}{{ nexus_default_context_path }}{{ nexus_rest_api_endpoint }}/{{ script_name }}/run"
    headers:
      Content-Type: "text/plain"
    method: POST
    status_code: 200,204
    body: "{{ args | to_json }}"
  environment:
    no_proxy: '127.0.0.1,localhost'
